# ClawCloud Deployment Configuration
# Optimized for 1 vCPU / 512MB RAM

apiVersion: v1
kind: Deployment
metadata:
  name: beacon-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beacon-server
  template:
    metadata:
      labels:
        app: beacon-server
    spec:
      containers:
      - name: beacon-server
        image: your-registry/beacon-server:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: NODE_OPTIONS
          value: "--max-old-space-size=384 --optimize-for-size"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: beacon-server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: beacon-server
