import nodemailer from 'nodemailer';
import { Resend } from 'resend';
import { logger } from './logger';
import dns from 'dns';

// Force IPv4 first for all connections in this process to avoid ENETUNREACH on IPv6-only/misconfigured hosts
if (dns.setDefaultResultOrder) {
  dns.setDefaultResultOrder('ipv4first');
}

const MAX_RETRIES = 1; // Faster fail on Railway 
const RETRY_BASE_DELAY = 1000; // ms

const BRAND_COLOR = '#5865F2';
const BRAND_NAME = 'Beacon';

/** Reusable HTML email wrapper */
function emailLayout(title: string, body: string): string {
  return `
    <!DOCTYPE html>
    <html lang="en" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <meta name="x-apple-disable-message-reformatting">
      <meta name="color-scheme" content="light dark">
      <meta name="supported-color-schemes" content="light dark">
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
        body { 
          font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; 
          margin: 0; 
          padding: 0; 
          background-color: #f3f4f6; 
          -webkit-font-smoothing: antialiased; 
          -moz-osx-font-smoothing: grayscale; 
        }
        table { border-collapse: collapse; }
        .email-wrapper { background-color: #f3f4f6; padding: 40px 20px; }
        .email-container { 
          background-color: #ffffff; 
          border-radius: 12px; 
          overflow: hidden; 
          box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03); 
          border: 1px solid #e5e7eb; 
          margin: 0 auto; 
          max-width: 600px;
          width: 100%;
        }
        .email-header { 
          background-color: #111827; 
          border-bottom: 4px solid ${BRAND_COLOR}; 
          padding: 40px 40px; 
          text-align: center; 
        }
        .email-body { padding: 48px 40px; }
        .email-footer { 
          padding: 32px 40px; 
          background-color: #f9fafb; 
          border-top: 1px solid #e5e7eb; 
          text-align: center; 
        }
        p { margin-top: 0; }
        @media only screen and (max-width: 600px) {
          .email-wrapper { padding: 20px 10px !important; }
          .email-body { padding: 32px 24px !important; }
          .email-header { padding: 32px 24px !important; }
          .email-footer { padding: 32px 24px !important; }
        }
      </style>
    </head>
    <body>
      <div style="display:none;font-size:1px;color:#f3f4f6;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;">
        Important update regarding your ${BRAND_NAME} account. &zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;
      </div>
      <table role="presentation" width="100%" class="email-wrapper">
        <tr><td align="center">
          <table role="presentation" class="email-container">
            <tr><td class="email-header">
              <h1 style="margin:0;color:#ffffff;font-size:24px;font-weight:700;letter-spacing:-0.025em;">${BRAND_NAME}</h1>
            </td></tr>
            <tr><td class="email-body">
              <h2 style="margin:0 0 24px;color:#111827;font-size:20px;font-weight:600;letter-spacing:-0.025em;">${title}</h2>
              ${body}
            </td></tr>
            <tr><td class="email-footer">
              <p style="margin:0;font-size:13px;color:#6b7280;line-height:1.6;">
                &copy; ${new Date().getFullYear()} ${BRAND_NAME}. All rights reserved.<br>
                <span style="display:block;margin-top:12px;font-size:12px;color:#9ca3af;">
                  This is an automated message generated by the ${BRAND_NAME} system.<br>Please do not reply directly to this email.
                </span>
              </p>
            </td></tr>
          </table>
        </td></tr>
      </table>
    </body>
    </html>
  `;
}

export class NotificationService {
  private static createTransporter(port: number) {
    const host = process.env.EMAIL_HOST || process.env.SMTP_HOST || 'smtp.gmail.com';
    const user = process.env.EMAIL_USER || process.env.SMTP_USER;
    const pass = (process.env.EMAIL_PASS || process.env.SMTP_PASS || '').replace(/\s+/g, '');

    return nodemailer.createTransport({
      host,
      port,
      secure: port === 465,
      auth: { user, pass },
      pool: true,
      maxConnections: 3,
      connectionTimeout: 5000,
      greetingTimeout: 5000,
      socketTimeout: 5000,
      tls: {
        rejectUnauthorized: process.env.NODE_ENV === 'production',
      },
    });
  }

  private static transporter = NotificationService.createTransporter(
    parseInt(process.env.EMAIL_PORT || process.env.SMTP_PORT || '587', 10)
  );

  private static resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;

  private static _verified = false;

  private static getFromAddress(aliasType: 'support' | 'noreply' = 'noreply') {
    const supportLabel = process.env.EMAIL_FROM_NAME || 'Beacon Support';
    const noreplyLabel = process.env.EMAIL_NOREPLY_NAME || 'Beacon Platform';

    if (aliasType === 'support') {
      const addr = process.env.EMAIL_SUPPORT_ADDRESS || 'support@beacon.qzz.io';
      return `"${supportLabel}" <${addr}>`;
    } else {
      const addr = process.env.EMAIL_NOREPLY_ADDRESS || 'noreply@beacon.qzz.io';
      return `"${noreplyLabel}" <${addr}>`;
    }
  }

  static async ensureConnection() {
    if (this._verified) return;

    if (this.resend || process.env.RESEND_API_KEY) {
      logger.success(`[EMAIL] Resend API Key detected on boot. Bypassing unsecure SMTP tests.`);
      this._verified = true;
      return;
    }

    const host = process.env.EMAIL_HOST || process.env.SMTP_HOST || 'smtp.gmail.com';
    const initialPort = parseInt(process.env.EMAIL_PORT || process.env.SMTP_PORT || '587', 10);
    const user = process.env.EMAIL_USER || process.env.SMTP_USER;
    const pass = (process.env.EMAIL_PASS || process.env.SMTP_PASS || '').replace(/\s+/g, '');

    if (!user || !pass) {
      logger.warn(`[EMAIL] Missing credentials for ${host}:${initialPort}. Running in DRY-RUN mode.`);
      return;
    }

    const tryConnect = async (port: number): Promise<boolean> => {
      try {
        logger.info(`[EMAIL] Testing SMTP: ${user}@${host}:${port} (SSL: ${port === 465})...`);
        const testTransporter = NotificationService.createTransporter(port);
        await testTransporter.verify();

        this.transporter = testTransporter;
        this._verified = true;
        logger.success(`[EMAIL] SMTP verified: ${host}:${port}`);
        return true;
      } catch (err: any) {
        let hint = '';
        if (err.responseCode === 535) {
          hint = ' -> ERROR: Invalid credentials. IF USING GMAIL, YOU MUST USE AN APP PASSWORD.';
        } else if (err.code === 'ETIMEDOUT' || err.code === 'ECONNREFUSED') {
          hint = ` -> ERROR: Port ${port} is blocked or unreachable.`;
        }

        logger.error(`[EMAIL] Failed at ${host}:${port}: ${err.message}${hint}`);
        return false;
      }
    };

    if (await tryConnect(initialPort)) return;

    const fallbacks = [465, 587, 2525].filter(p => p !== initialPort);
    
    for (const port of fallbacks) {
      logger.warn(`[EMAIL] Port ${initialPort} failed. Trying fallback port ${port}...`);
      if (await tryConnect(port)) return;
    }

    logger.error(`[EMAIL] FATAL: All SMTP ports (465, 587, 2525) failed. Railway may be blocking all outbound SMTP traffic. Consider using Resend or a dedicated Email API.`);
  }

  private static async sendWithRetry(mailOptions: nodemailer.SendMailOptions, dryRunMeta?: Record<string, string>): Promise<boolean> {
    const resendKey = process.env.RESEND_API_KEY;
    const user = process.env.EMAIL_USER || process.env.SMTP_USER;
    const pass = process.env.EMAIL_PASS || process.env.SMTP_PASS;

    if (this.resend && resendKey) {
      try {
        const { data, error } = await this.resend.emails.send({
          from: String(mailOptions.from || NotificationService.getFromAddress('noreply')),
          to: String(mailOptions.to),
          subject: String(mailOptions.subject),
          html: String(mailOptions.html),
        });

        if (error) {
          logger.warn(`[EMAIL] Resend API failed, falling back to SMTP: ${error.message}`);
        } else {
          logger.info(`[EMAIL] Sent "${mailOptions.subject}" via Resend: ${data?.id}`);
          return true;
        }
      } catch (error: any) {
        logger.warn(`[EMAIL] Resend API error: ${error.message}`);
      }
    }

    if (!user || !pass) {
      const metaLines = dryRunMeta
        ? Object.entries(dryRunMeta).map(([k, v]) => `  ${k}: ${v}`).join('\n')
        : '';
      logger.warn(
        `\n╔══════════════════════ EMAIL DRY-RUN ══════════════════════╗` +
        `\n  To:      ${mailOptions.to}` +
        `\n  Subject: ${mailOptions.subject}` +
        (metaLines ? `\n${metaLines}` : '') +
        `\n╚══════════════════════════════════════════════════════════╝`
      );
      return true;
    }

    await this.ensureConnection();

    for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
      try {
        await this.transporter.sendMail(mailOptions);
        logger.info(`[EMAIL] Sent "${mailOptions.subject}" via SMTP to ${mailOptions.to}`);
        return true;
      } catch (error: any) {
        const isRetryable = error.responseCode >= 400 || error.code === 'ECONNECTION' || error.code === 'ETIMEDOUT';
        if (attempt < MAX_RETRIES && isRetryable) {
          const delay = RETRY_BASE_DELAY * Math.pow(2, attempt - 1);
          logger.warn(`[EMAIL] Attempt ${attempt}/${MAX_RETRIES} failed, retrying in ${delay}ms: ${error.message}`);
          await new Promise(resolve => setTimeout(resolve, delay));
        } else {
          logger.error(`[EMAIL] Failed after ${attempt} attempts to send "${mailOptions.subject}" via SMTP: ${error.message}`);
          return false;
        }
      }
    }
    return false;
  }

  static async sendVerificationCode(email: string, code: string) {
    return this.sendWithRetry({
      from: this.getFromAddress('noreply'),
      to: email,
      subject: 'Verify Your Beacon Account',
      html: emailLayout('Verify Your Email', `
        <p style="color:#374151;font-size:16px;line-height:1.625;margin:0 0 32px;">
          Welcome to ${BRAND_NAME}! To complete your registration and secure your account, please enter the verification code below.
        </p>
        <div style="background-color:#F2F4FF;border:1px solid #D6DDFB;border-radius:8px;padding:32px 24px;text-align:center;margin:0 0 32px;">
          <span style="font-family:ui-monospace, 'Cascadia Mono', 'Segoe UI Mono', 'Liberation Mono', Menlo, Monaco, Consolas, monospace;font-size:36px;font-weight:700;letter-spacing:10px;color:${BRAND_COLOR};display:inline-block;margin-left:10px;">
            ${code}
          </span>
        </div>
        <p style="color:#6b7280;font-size:14px;line-height:1.6;margin:0;">
          This code expires in <strong>24 hours</strong>. If you didn't attempt to create a ${BRAND_NAME} account, you can safely ignore and delete this email.
        </p>
      `),
    }, { 'Verification Code': code });
  }

  static async sendPasswordReset(email: string, token: string) {
    const resetUrl = `${process.env.FRONTEND_URL || 'http://localhost:5173'}/auth/reset-password?token=${token}`;

    return this.sendWithRetry({
      from: this.getFromAddress('noreply'),
      to: email,
      subject: 'Reset Your Beacon Password',
      html: emailLayout('Reset Your Password', `
        <p style="color:#374151;font-size:16px;line-height:1.625;margin:0 0 32px;">
          We received a request to reset the password for your ${BRAND_NAME} account. Click the button below to choose a new password.
        </p>
        <div style="text-align:center;margin:0 0 32px;">
          <a href="${resetUrl}" style="display:inline-block;padding:14px 32px;background-color:${BRAND_COLOR};color:#ffffff;text-decoration:none;border-radius:6px;font-weight:600;font-size:16px;box-shadow:0 4px 6px -1px rgba(88, 101, 242, 0.2);">
            Reset Password
          </a>
        </div>
        <p style="color:#6b7280;font-size:14px;line-height:1.6;margin:0 0 12px;">
          This link expires in <strong>1 hour</strong>. If the button doesn't work, copy and paste this URL into your browser:
        </p>
        <div style="background-color:#f8fafc;padding:16px;border-radius:6px;border:1px dashed #cbd5e1;">
          <a href="${resetUrl}" style="color:${BRAND_COLOR};font-size:13px;word-break:break-all;text-decoration:none;line-height:1.5;">
            ${resetUrl}
          </a>
        </div>
      `),
    }, { 'Reset Token': token, 'Reset URL': resetUrl });
  }

  static async sendWelcomeEmail(email: string, username: string) {
    // Custom Checkmark CSS Icon
    const checkIcon = `<span style="display:inline-block;width:20px;height:20px;background-color:#e0e7ff;color:${BRAND_COLOR};border-radius:50%;text-align:center;line-height:20px;font-size:12px;font-weight:bold;margin-right:12px;vertical-align:middle;">&#10003;</span>`;

    return this.sendWithRetry({
      from: this.getFromAddress('noreply'),
      to: email,
      subject: 'Welcome to Beacon!',
      html: emailLayout(`Welcome, ${username}!`, `
        <p style="color:#374151;font-size:16px;line-height:1.625;margin:0 0 24px;">
          Your account is successfully verified and ready to go. We are thrilled to have you here!
        </p>
        <p style="color:#374151;font-size:16px;line-height:1.625;margin:0 0 16px;font-weight:500;">
          Here are a few things you can do to get started:
        </p>
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 32px;">
          <tr>
            <td style="padding-bottom:12px;color:#374151;font-size:15px;line-height:1.6;">
              ${checkIcon} <strong>Create or join a server</strong> to start chatting
            </td>
          </tr>
          <tr>
            <td style="padding-bottom:12px;color:#374151;font-size:15px;line-height:1.6;">
              ${checkIcon} <strong>Customize your profile</strong> with an avatar and bio
            </td>
          </tr>
          <tr>
            <td style="padding-bottom:12px;color:#374151;font-size:15px;line-height:1.6;">
              ${checkIcon} <strong>Invite friends</strong> to your space
            </td>
          </tr>
        </table>
        <div style="text-align:center;">
          <a href="${process.env.FRONTEND_URL || 'https://beacon.qzz.io'}" style="display:inline-block;padding:14px 32px;background-color:${BRAND_COLOR};color:#ffffff;text-decoration:none;border-radius:6px;font-weight:600;font-size:16px;box-shadow:0 4px 6px -1px rgba(88, 101, 242, 0.2);">
            Open ${BRAND_NAME}
          </a>
        </div>
      `),
    });
  }

  static async sendSecurityAlert(email: string, reason: string) {
    // Custom Alert CSS Icon
    const alertIcon = `<span style="display:inline-block;width:22px;height:22px;background-color:#ef4444;color:#ffffff;border-radius:50%;text-align:center;line-height:22px;font-size:14px;font-weight:bold;margin-right:10px;vertical-align:middle;">!</span>`;

    return this.sendWithRetry({
      from: this.getFromAddress('support'),
      to: email,
      subject: 'Beacon Security Alert',
      html: emailLayout('Security Alert', `
        <div style="background-color:#fef2f2;border-left:4px solid #ef4444;border-radius:6px;padding:20px 24px;margin:0 0 32px;">
          <p style="color:#991b1b;font-size:16px;line-height:1.6;margin:0;font-weight:500;">
            ${alertIcon} ${reason}
          </p>
        </div>
        <p style="color:#374151;font-size:16px;line-height:1.625;margin:0 0 32px;">
          If this was you, no further action is needed. If you do not recognize this activity, please secure your account immediately by changing your password.
        </p>
        <div style="text-align:center;">
          <a href="${process.env.FRONTEND_URL || 'https://beacon.qzz.io'}/settings/security" style="display:inline-block;padding:14px 32px;background-color:#ef4444;color:#ffffff;text-decoration:none;border-radius:6px;font-weight:600;font-size:16px;box-shadow:0 4px 6px -1px rgba(239, 68, 68, 0.2);">
            Review Security Settings
          </a>
        </div>
      `),
    });
  }

  static async sendBackupNotice(email: string) {
    // Custom Success CSS Icon
    const successIcon = `<span style="display:inline-block;width:16px;height:16px;background-color:#059669;color:#ffffff;border-radius:50%;text-align:center;line-height:16px;font-size:10px;font-weight:bold;margin-right:6px;vertical-align:middle;">&#10003;</span>`;

    return this.sendWithRetry({
      from: this.getFromAddress('noreply'),
      to: email,
      subject: 'Your Beacon Server Backup is Ready',
      html: emailLayout('Backup Complete', `
        <div style="text-align:center;margin-bottom:24px;">
          <span style="display:inline-block;background-color:#ecfdf5;color:#059669;padding:8px 16px;border-radius:20px;font-size:14px;font-weight:600;">
            ${successIcon} Status: Success
          </span>
        </div>
        <p style="color:#374151;font-size:16px;line-height:1.625;margin:0 0 16px;">
          Your requested server backup has been generated successfully and is now ready for download.
        </p>
        <p style="color:#6b7280;font-size:15px;line-height:1.625;margin:0;">
          You can access your backup file directly from your server settings. Please note that backups are retained securely on our servers for <strong>7 days</strong>.
        </p>
      `),
    });
  }

  static async sendSystemUpdateNotice(email: string, version: string, releaseNotes: string) {
    return this.sendWithRetry({
      from: this.getFromAddress('noreply'),
      to: email,
      subject: `Beacon ${version} Update`,
      html: emailLayout(`What's new in Beacon ${version}`, `
        <p style="color:#374151;font-size:16px;line-height:1.625;margin:0 0 24px;">
          We've just released a major update to ${BRAND_NAME}. Here is a quick look at what has changed:
        </p>
        <div style="background-color:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:24px;margin:0 0 32px;color:#334155;font-size:14px;line-height:1.7;">
          ${releaseNotes}
        </div>
        <div style="text-align:center;">
          <a href="${process.env.FRONTEND_URL || 'https://beacon.qzz.io'}/updates" style="display:inline-block;padding:14px 32px;background-color:${BRAND_COLOR};color:#ffffff;text-decoration:none;border-radius:6px;font-weight:600;font-size:16px;box-shadow:0 4px 6px -1px rgba(88, 101, 242, 0.2);">
            Read Full Patch Notes
          </a>
        </div>
      `),
    });
  }
}